import './globals.css'

export const metadata = {
  title: 'Teste api 2FA de firebase',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='min-h-[100vh] flex flex-col justify-center items-center'>{children}</body>
    </html>
  )
}
